import streamlit as st
from dream_utils import interpret_dream, get_dream_advice, chat_with_dream_ai
from gtts import gTTS
import os
import tempfile

# Page config
st.set_page_config(
    page_title="🧠 AI Dream Interpreter + Assistant",
    page_icon="🌙",
    layout="centered"
)

# Custom CSS for beautiful UI
st.markdown("""
    <style>
    .main {
        background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
        color: white;
    }
    .stTextInput > div > div > input {
        background-color: #1e1e2f;
        color: white;
        border-radius: 20px;
        padding: 15px;
    }
    .stTextArea > div > div > textarea {
        background-color: #1e1e2f;
        color: white;
        border-radius: 20px;
        padding: 15px;
    }
    .dream-card {
        background: rgba(255,255,255,0.08);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 30px;
        margin: 20px 0;
        border: 1px solid rgba(255,255,255,0.1);
    }
    .chat-message {
        padding: 15px;
        border-radius: 15px;
        margin: 10px 0;
    }
    .user-message {
        background: rgba(52, 152, 219, 0.2);
        border-left: 4px solid #3498db;
    }
    .assistant-message {
        background: rgba(46, 204, 113, 0.2);
        border-left: 4px solid #2ecc71;
    }
    </style>
""", unsafe_allow_html=True)

# Initialize session state
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = []
if 'dream_interpreted' not in st.session_state:
    st.session_state.dream_interpreted = ""
if 'journal' not in st.session_state:
    st.session_state.journal = []

# Title
st.title("🌙 AI Dream Interpreter + Assistant")
st.markdown("*Unlock the hidden messages in your dreams and chat with your personal dream analyst*")

# Tab layout
tab1, tab2, tab3 = st.tabs(["🔮 Interpret Dream", "💬 Chat with Assistant", "📖 Dream Journal"])

# --- TAB 1: Interpret Dream ---
with tab1:
    dream_text = st.text_area(
        "Describe your dream in detail:",
        placeholder="I was flying over a city, then I fell into the ocean...",
        height=150
    )
    
    col1, col2 = st.columns(2)
    with col1:
        interpret_btn = st.button("🔮 Interpret My Dream", use_container_width=True)
    with col2:
        clear_btn = st.button("🗑️ Clear", use_container_width=True)
    
    if clear_btn:
        dream_text = ""
        st.rerun()
    
    if interpret_btn and dream_text:
        with st.spinner("🔮 Analyzing your dream..."):
            # Get interpretation
            interpretation = interpret_dream(dream_text)
            advice = get_dream_advice(interpretation)
            
            # Store for chat
            st.session_state.dream_interpreted = dream_text
            
            # Display results
            st.markdown("---")
            st.markdown('<div class="dream-card">', unsafe_allow_html=True)
            
            st.subheader("🧠 Interpretation")
            st.write(interpretation)
            
            st.subheader("💡 Advice for Today")
            st.info(advice)
            
            st.caption("🔍 *This interpretation is generated by AI and is for entertainment purposes.*")
            
            st.markdown('</div>', unsafe_allow_html=True)
            
            # Text-to-speech
            if st.button("🔊 Listen to Interpretation"):
                tts = gTTS(text=interpretation, lang='en', slow=False)
                with tempfile.NamedTemporaryFile(delete=False, suffix='.mp3') as fp:
                    tts.save(fp.name)
                    audio_file = open(fp.name, 'rb')
                    audio_bytes = audio_file.read()
                    st.audio(audio_bytes, format='audio/mp3')
                    audio_file.close()
                    os.unlink(fp.name)
            
            # Save to journal
            if st.button("📖 Save to Dream Journal"):
                st.session_state.journal.append({
                    'dream': dream_text,
                    'interpretation': interpretation,
                    'advice': advice
                })
                st.success("✅ Dream saved to your journal!")
    
    elif interpret_btn and not dream_text:
        st.warning("⚠️ Please describe your dream first!")

# --- TAB 2: Chat with Assistant ---
with tab2:
    st.subheader("💬 Ask your Dream Assistant")
    st.caption("Ask follow-up questions about your dream and get personalized insights")
    
    if not st.session_state.dream_interpreted:
        st.info("👆 First, go to the 'Interpret Dream' tab and analyze your dream!")
    else:
        # Display dream context
        with st.expander("📝 Your Dream Context"):
            st.write(st.session_state.dream_interpreted)
        
        # Chat interface
        chat_container = st.container()
        with chat_container:
            for msg in st.session_state.chat_history:
                if msg['role'] == 'user':
                    st.markdown(f'<div class="chat-message user-message">👤 <b>You:</b> {msg["content"]}</div>', unsafe_allow_html=True)
                else:
                    st.markdown(f'<div class="chat-message assistant-message">🤖 <b>Assistant:</b> {msg["content"]}</div>', unsafe_allow_html=True)
        
        # Chat input
        user_question = st.text_input("Ask a question about your dream:", placeholder="What does flying mean in my dream?")
        
        col1, col2 = st.columns([4, 1])
        with col1:
            send_btn = st.button("📤 Send", use_container_width=True)
        with col2:
            clear_chat_btn = st.button("🗑️ Clear Chat", use_container_width=True)
        
        if clear_chat_btn:
            st.session_state.chat_history = []
            st.rerun()
        
        if send_btn and user_question:
            with st.spinner("🤔 Thinking..."):
                # Get AI response
                response = chat_with_dream_ai(user_question, st.session_state.dream_interpreted)
                
                # Add to chat history
                st.session_state.chat_history.append({'role': 'user', 'content': user_question})
                st.session_state.chat_history.append({'role': 'assistant', 'content': response})
                
                # Rerun to update chat
                st.rerun()
        
        # Quick question suggestions
        st.caption("💡 **Try asking:**")
        quick_questions = [
            "What does this dream say about my current life?",
            "Is this dream a warning or a positive sign?",
            "Why did I dream about [specific element]?",
            "What should I do after having this dream?"
        ]
        
        cols = st.columns(2)
        for i, q in enumerate(quick_questions):
            with cols[i % 2]:
                if st.button(q, use_container_width=True):
                    # Auto-fill the question
                    st.session_state._temp_question = q
                    st.rerun()

# --- TAB 3: Dream Journal ---
with tab3:
    st.subheader("📖 Your Dream Journal")
    
    if not st.session_state.journal:
        st.info("No dreams saved yet. Interpret a dream and save it to your journal!")
    else:
        for i, entry in enumerate(reversed(st.session_state.journal)):
            with st.expander(f"🌙 Dream #{len(st.session_state.journal) - i}"):
                st.write(f"**Dream:** {entry['dream']}")
                st.write(f"**Interpretation:** {entry['interpretation']}")
                st.write(f"**Advice:** {entry['advice']}")
                st.caption(f"Saved: {i+1} days ago")
        
        if st.button("🗑️ Clear All Journal Entries"):
            st.session_state.journal = []
            st.rerun()
    
    # Journal stats
    if st.session_state.journal:
        st.subheader("📊 Dream Stats")
        total_dreams = len(st.session_state.journal)
        st.metric("Total Dreams Interpreted", total_dreams)
        
        # Simple word cloud idea (optional)
        st.caption("🔮 *Track your dream patterns over time!*")

# Footer
st.markdown("---")
st.caption("🌙 *AI Dream Interpreter v2.0 — Built with Streamlit, GPT-2 & DialoGPT*")